[package]
name = "delfin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.1.6"
itertools = "0.10.3"
regex = "1.1.6"
rust_decimal = "1.25"
rust_decimal_macros = "1.25"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
slice-group-by = "0.3.0"
thiserror = "1.0.31"

[dev-dependencies]
claim = "0.5"
fake = { version = "2.5.0", features = ["chrono"] }
quickcheck = "1"
quickcheck_macros = "1.0.0"
