[package]
name = "for-importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
rust_decimal = "1.25"
rust_decimal_macros = "1.25"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
